Vol 26/discover tab
UoaWDCC/volunteers pull request #60
Opened 2024-04-28 23:55 UTC by jerry2005hn

Fixed the container css in discovery, complete the discovery tab.

2024-04-29 09:49 UTC, John-Moore-UOA approved these changes
lgtm

2024-04-30 01:54 UTC, dis-may commented on web/src/pages/MainMenu.tsx
Don't commit this file, since your component would go on the Dashboard page (which hasn't been made yet) and not the MainMenu page. It's ok to use it to preview your component though. Could you edit your commit so it does not include this file? After that its all ok to merge, thanks!

2024-04-30 01:57 UTC, dis-may requested changes
Don't commit your changes to MainMenu.tsx, since you're just using that to preview your component. After that, you are good to merge :))

2024-04-30 05:27 UTC, dis-may approved these changes

2024-04-30 05:27 UTC, merged